/**
 * Amazon Shipping API
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Address } from './Address.js'
import { GenerationStatus } from './GenerationStatus.js'

/**
 * The CollectionFormsHistoryRecord model module.
 * @module shipping_v2/model/CollectionFormsHistoryRecord
 * @version v2
 */
export class CollectionFormsHistoryRecord {
  /**
   * Constructs a new <code>CollectionFormsHistoryRecord</code>.
   * Active Account Details
   * @alias module:shipping_v2/model/CollectionFormsHistoryRecord
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>CollectionFormsHistoryRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {CollectionFormsHistoryRecord} obj Optional instance to populate.
   * @return {CollectionFormsHistoryRecord} The populated <code>CollectionFormsHistoryRecord</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new CollectionFormsHistoryRecord()
      if (data.hasOwnProperty('carrierName')) { obj.carrierName = ApiClient.convertToType(data.carrierName, 'String') }
      if (data.hasOwnProperty('creationDate')) { obj.creationDate = ApiClient.convertToType(data.creationDate, 'String') }
      if (data.hasOwnProperty('generationStatus')) { obj.generationStatus = GenerationStatus.constructFromObject(data.generationStatus) }
      if (data.hasOwnProperty('collectionFormId')) { obj.collectionFormId = ApiClient.convertToType(data.collectionFormId, 'String') }
      if (data.hasOwnProperty('shipFromAddress')) { obj.shipFromAddress = Address.constructFromObject(data.shipFromAddress) }
    }
    return obj
  }
}

/**
 * The carrier name for the offering.
 * @member {String} carrierName
 * @type {String}
 */
CollectionFormsHistoryRecord.prototype.carrierName = undefined

/**
 * Creation Time for this account.
 * @member {String} creationDate
 * @type {String}
 */
CollectionFormsHistoryRecord.prototype.creationDate = undefined

/**
 * @member {GenerationStatus} generationStatus
 * @type {GenerationStatus}
 */
CollectionFormsHistoryRecord.prototype.generationStatus = undefined

/**
 * Collection Form Id for Reprint .
 * @member {String} collectionFormId
 * @type {String}
 */
CollectionFormsHistoryRecord.prototype.collectionFormId = undefined

/**
 * @member {Address} shipFromAddress
 * @type {Address}
 */
CollectionFormsHistoryRecord.prototype.shipFromAddress = undefined
