/**
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { Address } from './Address.js'
import { AutomatedShippingSettings } from './AutomatedShippingSettings.js'
import { BuyerInfo } from './BuyerInfo.js'
import { BuyerTaxInformation } from './BuyerTaxInformation.js'
import { EasyShipShipmentStatus } from './EasyShipShipmentStatus.js'
import { ElectronicInvoiceStatus } from './ElectronicInvoiceStatus.js'
import { FulfillmentInstruction } from './FulfillmentInstruction.js'
import { MarketplaceTaxInfo } from './MarketplaceTaxInfo.js'
import { Money } from './Money.js'
import { PaymentExecutionDetailItem } from './PaymentExecutionDetailItem.js'

/**
 * The Order model module.
 * @module orders_v0/model/Order
 * @version v0
 */
export class Order {
  /**
   * Constructs a new <code>Order</code>.
   * Order information.
   * @alias module:orders_v0/model/Order
   * @class
   * @param amazonOrderId {String} An Amazon-defined order identifier, in 3-7-7 format.
   * @param purchaseDate {String} The date when the order was created.
   * @param lastUpdateDate {String} The date when the order was last updated.  __Note__: `LastUpdateDate` is returned with an incorrect date for orders that were last updated before 2009-04-01.
   * @param orderStatus {String} The current order status.
   */
  constructor (amazonOrderId, purchaseDate, lastUpdateDate, orderStatus) {
    this.amazonOrderId = amazonOrderId
    this.purchaseDate = purchaseDate
    this.lastUpdateDate = lastUpdateDate
    this.orderStatus = orderStatus
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {Order} obj Optional instance to populate.
   * @return {Order} The populated <code>Order</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new Order()
      if (data.hasOwnProperty('AmazonOrderId')) { obj.amazonOrderId = ApiClient.convertToType(data.AmazonOrderId, 'String') }
      if (data.hasOwnProperty('SellerOrderId')) { obj.sellerOrderId = ApiClient.convertToType(data.SellerOrderId, 'String') }
      if (data.hasOwnProperty('PurchaseDate')) { obj.purchaseDate = ApiClient.convertToType(data.PurchaseDate, 'String') }
      if (data.hasOwnProperty('LastUpdateDate')) { obj.lastUpdateDate = ApiClient.convertToType(data.LastUpdateDate, 'String') }
      if (data.hasOwnProperty('OrderStatus')) { obj.orderStatus = ApiClient.convertToType(data.OrderStatus, 'String') }
      if (data.hasOwnProperty('FulfillmentChannel')) { obj.fulfillmentChannel = ApiClient.convertToType(data.FulfillmentChannel, 'String') }
      if (data.hasOwnProperty('SalesChannel')) { obj.salesChannel = ApiClient.convertToType(data.SalesChannel, 'String') }
      if (data.hasOwnProperty('OrderChannel')) { obj.orderChannel = ApiClient.convertToType(data.OrderChannel, 'String') }
      if (data.hasOwnProperty('ShipServiceLevel')) { obj.shipServiceLevel = ApiClient.convertToType(data.ShipServiceLevel, 'String') }
      if (data.hasOwnProperty('OrderTotal')) { obj.orderTotal = Money.constructFromObject(data.OrderTotal) }
      if (data.hasOwnProperty('NumberOfItemsShipped')) { obj.numberOfItemsShipped = ApiClient.convertToType(data.NumberOfItemsShipped, 'Number') }
      if (data.hasOwnProperty('NumberOfItemsUnshipped')) { obj.numberOfItemsUnshipped = ApiClient.convertToType(data.NumberOfItemsUnshipped, 'Number') }
      if (data.hasOwnProperty('PaymentExecutionDetail')) { obj.paymentExecutionDetail = ApiClient.convertToType(data.PaymentExecutionDetail, [PaymentExecutionDetailItem]) }
      if (data.hasOwnProperty('PaymentMethod')) { obj.paymentMethod = ApiClient.convertToType(data.PaymentMethod, 'String') }
      if (data.hasOwnProperty('PaymentMethodDetails')) { obj.paymentMethodDetails = ApiClient.convertToType(data.PaymentMethodDetails, ['String']) }
      if (data.hasOwnProperty('MarketplaceId')) { obj.marketplaceId = ApiClient.convertToType(data.MarketplaceId, 'String') }
      if (data.hasOwnProperty('ShipmentServiceLevelCategory')) { obj.shipmentServiceLevelCategory = ApiClient.convertToType(data.ShipmentServiceLevelCategory, 'String') }
      if (data.hasOwnProperty('EasyShipShipmentStatus')) { obj.easyShipShipmentStatus = EasyShipShipmentStatus.constructFromObject(data.EasyShipShipmentStatus) }
      if (data.hasOwnProperty('CbaDisplayableShippingLabel')) { obj.cbaDisplayableShippingLabel = ApiClient.convertToType(data.CbaDisplayableShippingLabel, 'String') }
      if (data.hasOwnProperty('OrderType')) { obj.orderType = ApiClient.convertToType(data.OrderType, 'String') }
      if (data.hasOwnProperty('EarliestShipDate')) { obj.earliestShipDate = ApiClient.convertToType(data.EarliestShipDate, 'String') }
      if (data.hasOwnProperty('LatestShipDate')) { obj.latestShipDate = ApiClient.convertToType(data.LatestShipDate, 'String') }
      if (data.hasOwnProperty('EarliestDeliveryDate')) { obj.earliestDeliveryDate = ApiClient.convertToType(data.EarliestDeliveryDate, 'String') }
      if (data.hasOwnProperty('LatestDeliveryDate')) { obj.latestDeliveryDate = ApiClient.convertToType(data.LatestDeliveryDate, 'String') }
      if (data.hasOwnProperty('IsBusinessOrder')) { obj.isBusinessOrder = ApiClient.convertToType(data.IsBusinessOrder, 'Boolean') }
      if (data.hasOwnProperty('IsPrime')) { obj.isPrime = ApiClient.convertToType(data.IsPrime, 'Boolean') }
      if (data.hasOwnProperty('IsPremiumOrder')) { obj.isPremiumOrder = ApiClient.convertToType(data.IsPremiumOrder, 'Boolean') }
      if (data.hasOwnProperty('IsGlobalExpressEnabled')) { obj.isGlobalExpressEnabled = ApiClient.convertToType(data.IsGlobalExpressEnabled, 'Boolean') }
      if (data.hasOwnProperty('ReplacedOrderId')) { obj.replacedOrderId = ApiClient.convertToType(data.ReplacedOrderId, 'String') }
      if (data.hasOwnProperty('IsReplacementOrder')) { obj.isReplacementOrder = ApiClient.convertToType(data.IsReplacementOrder, 'Boolean') }
      if (data.hasOwnProperty('PromiseResponseDueDate')) { obj.promiseResponseDueDate = ApiClient.convertToType(data.PromiseResponseDueDate, 'String') }
      if (data.hasOwnProperty('IsEstimatedShipDateSet')) { obj.isEstimatedShipDateSet = ApiClient.convertToType(data.IsEstimatedShipDateSet, 'Boolean') }
      if (data.hasOwnProperty('IsSoldByAB')) { obj.isSoldByAB = ApiClient.convertToType(data.IsSoldByAB, 'Boolean') }
      if (data.hasOwnProperty('IsIBA')) { obj.isIBA = ApiClient.convertToType(data.IsIBA, 'Boolean') }
      if (data.hasOwnProperty('DefaultShipFromLocationAddress')) { obj.defaultShipFromLocationAddress = Address.constructFromObject(data.DefaultShipFromLocationAddress) }
      if (data.hasOwnProperty('BuyerInvoicePreference')) { obj.buyerInvoicePreference = ApiClient.convertToType(data.BuyerInvoicePreference, 'String') }
      if (data.hasOwnProperty('BuyerTaxInformation')) { obj.buyerTaxInformation = BuyerTaxInformation.constructFromObject(data.BuyerTaxInformation) }
      if (data.hasOwnProperty('FulfillmentInstruction')) { obj.fulfillmentInstruction = FulfillmentInstruction.constructFromObject(data.FulfillmentInstruction) }
      if (data.hasOwnProperty('IsISPU')) { obj.isISPU = ApiClient.convertToType(data.IsISPU, 'Boolean') }
      if (data.hasOwnProperty('IsAccessPointOrder')) { obj.isAccessPointOrder = ApiClient.convertToType(data.IsAccessPointOrder, 'Boolean') }
      if (data.hasOwnProperty('MarketplaceTaxInfo')) { obj.marketplaceTaxInfo = MarketplaceTaxInfo.constructFromObject(data.MarketplaceTaxInfo) }
      if (data.hasOwnProperty('SellerDisplayName')) { obj.sellerDisplayName = ApiClient.convertToType(data.SellerDisplayName, 'String') }
      if (data.hasOwnProperty('ShippingAddress')) { obj.shippingAddress = Address.constructFromObject(data.ShippingAddress) }
      if (data.hasOwnProperty('BuyerInfo')) { obj.buyerInfo = BuyerInfo.constructFromObject(data.BuyerInfo) }
      if (data.hasOwnProperty('AutomatedShippingSettings')) { obj.automatedShippingSettings = AutomatedShippingSettings.constructFromObject(data.AutomatedShippingSettings) }
      if (data.hasOwnProperty('HasRegulatedItems')) { obj.hasRegulatedItems = ApiClient.convertToType(data.HasRegulatedItems, 'Boolean') }
      if (data.hasOwnProperty('ElectronicInvoiceStatus')) { obj.electronicInvoiceStatus = ElectronicInvoiceStatus.constructFromObject(data.ElectronicInvoiceStatus) }
    }
    return obj
  }
}

/**
 * An Amazon-defined order identifier, in 3-7-7 format.
 * @member {String} amazonOrderId
 * @type {String}
 */
Order.prototype.amazonOrderId = undefined

/**
 * A seller-defined order identifier.
 * @member {String} sellerOrderId
 * @type {String}
 */
Order.prototype.sellerOrderId = undefined

/**
 * The date when the order was created.
 * @member {String} purchaseDate
 * @type {String}
 */
Order.prototype.purchaseDate = undefined

/**
 * The date when the order was last updated.  __Note__: `LastUpdateDate` is returned with an incorrect date for orders that were last updated before 2009-04-01.
 * @member {String} lastUpdateDate
 * @type {String}
 */
Order.prototype.lastUpdateDate = undefined

/**
 * Allowed values for the <code>OrderStatus</code> property.
 * @enum {String}
 * @readonly
 */
Order.OrderStatusEnum = {

  /**
     * value: "Pending"
     * @const
     */
  Pending: 'Pending',

  /**
     * value: "Unshipped"
     * @const
     */
  Unshipped: 'Unshipped',

  /**
     * value: "PartiallyShipped"
     * @const
     */
  PartiallyShipped: 'PartiallyShipped',

  /**
     * value: "Shipped"
     * @const
     */
  Shipped: 'Shipped',

  /**
     * value: "Canceled"
     * @const
     */
  Canceled: 'Canceled',

  /**
     * value: "Unfulfillable"
     * @const
     */
  Unfulfillable: 'Unfulfillable',

  /**
     * value: "InvoiceUnconfirmed"
     * @const
     */
  InvoiceUnconfirmed: 'InvoiceUnconfirmed',

  /**
     * value: "PendingAvailability"
     * @const
     */
  PendingAvailability: 'PendingAvailability'
}

/**
 * The current order status.
 * @member {String} orderStatus
 * @type {String}
 */
Order.prototype.orderStatus = undefined

/**
 * Allowed values for the <code>FulfillmentChannel</code> property.
 * @enum {String}
 * @readonly
 */
Order.FulfillmentChannelEnum = {

  /**
     * value: "MFN"
     * @const
     */
  MFN: 'MFN',

  /**
     * value: "AFN"
     * @const
     */
  AFN: 'AFN'
}

/**
 * Whether the order was fulfilled by Amazon (`AFN`) or by the seller (`MFN`).
 * @member {String} fulfillmentChannel
 * @type {String}
 */
Order.prototype.fulfillmentChannel = undefined

/**
 * The sales channel for the first item in the order.
 * @member {String} salesChannel
 * @type {String}
 */
Order.prototype.salesChannel = undefined

/**
 * The order channel for the first item in the order.
 * @member {String} orderChannel
 * @type {String}
 */
Order.prototype.orderChannel = undefined

/**
 * The order's shipment service level.
 * @member {String} shipServiceLevel
 * @type {String}
 */
Order.prototype.shipServiceLevel = undefined

/**
 * @member {Money} orderTotal
 * @type {Money}
 */
Order.prototype.orderTotal = undefined

/**
 * The number of items shipped.
 * @member {Number} numberOfItemsShipped
 * @type {Number}
 */
Order.prototype.numberOfItemsShipped = undefined

/**
 * The number of items unshipped.
 * @member {Number} numberOfItemsUnshipped
 * @type {Number}
 */
Order.prototype.numberOfItemsUnshipped = undefined

/**
 * A list of payment execution detail items.
 * @member {[PaymentExecutionDetailItem]} paymentExecutionDetail
 * @type {[PaymentExecutionDetailItem]}
 */
Order.prototype.paymentExecutionDetail = undefined

/**
 * Allowed values for the <code>PaymentMethod</code> property.
 * @enum {String}
 * @readonly
 */
Order.PaymentMethodEnum = {

  /**
     * value: "COD"
     * @const
     */
  COD: 'COD',

  /**
     * value: "CVS"
     * @const
     */
  CVS: 'CVS',

  /**
     * value: "Other"
     * @const
     */
  Other: 'Other'
}

/**
 * The payment method for the order. This property is limited to COD and CVS payment methods. Unless you need the specific COD payment information provided by the `PaymentExecutionDetailItem` object, we recommend using the `PaymentMethodDetails` property to get payment method information.
 * @member {String} paymentMethod
 * @type {String}
 */
Order.prototype.paymentMethod = undefined

/**
 * A list of payment method detail items.
 * @member {[String]} paymentMethodDetails
 * @type {[String]}
 */
Order.prototype.paymentMethodDetails = undefined

/**
 * The identifier for the marketplace where the order was placed.
 * @member {String} marketplaceId
 * @type {String}
 */
Order.prototype.marketplaceId = undefined

/**
 * The shipment service level category for the order.  **Possible values**: `Expedited`, `FreeEconomy`, `NextDay`, `Priority`, `SameDay`, `SecondDay`, `Scheduled`, and `Standard`.
 * @member {String} shipmentServiceLevelCategory
 * @type {String}
 */
Order.prototype.shipmentServiceLevelCategory = undefined

/**
 * @member {EasyShipShipmentStatus} easyShipShipmentStatus
 * @type {EasyShipShipmentStatus}
 */
Order.prototype.easyShipShipmentStatus = undefined

/**
 * Custom ship label for Checkout by Amazon (CBA).
 * @member {String} cbaDisplayableShippingLabel
 * @type {String}
 */
Order.prototype.cbaDisplayableShippingLabel = undefined

/**
 * Allowed values for the <code>OrderType</code> property.
 * @enum {String}
 * @readonly
 */
Order.OrderTypeEnum = {

  /**
     * value: "StandardOrder"
     * @const
     */
  StandardOrder: 'StandardOrder',

  /**
     * value: "LongLeadTimeOrder"
     * @const
     */
  LongLeadTimeOrder: 'LongLeadTimeOrder',

  /**
     * value: "Preorder"
     * @const
     */
  Preorder: 'Preorder',

  /**
     * value: "BackOrder"
     * @const
     */
  BackOrder: 'BackOrder',

  /**
     * value: "SourcingOnDemandOrder"
     * @const
     */
  SourcingOnDemandOrder: 'SourcingOnDemandOrder'
}

/**
 * The order's type.
 * @member {String} orderType
 * @type {String}
 */
Order.prototype.orderType = undefined

/**
 * The start of the time period within which you have committed to ship the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders.  __Note__: `EarliestShipDate` might not be returned for orders placed before February 1, 2013.
 * @member {String} earliestShipDate
 * @type {String}
 */
Order.prototype.earliestShipDate = undefined

/**
 * The end of the time period within which you have committed to ship the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders.  __Note__: `LatestShipDate` might not be returned for orders placed before February 1, 2013.
 * @member {String} latestShipDate
 * @type {String}
 */
Order.prototype.latestShipDate = undefined

/**
 * The start of the time period within which you have committed to fulfill the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders.
 * @member {String} earliestDeliveryDate
 * @type {String}
 */
Order.prototype.earliestDeliveryDate = undefined

/**
 * The end of the time period within which you have committed to fulfill the order. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date time format. Only returned for seller-fulfilled orders that do not have a `PendingAvailability`, `Pending`, or `Canceled` status.
 * @member {String} latestDeliveryDate
 * @type {String}
 */
Order.prototype.latestDeliveryDate = undefined

/**
 * When true, the order is an Amazon Business order. An Amazon Business order is an order where the buyer is a Verified Business Buyer.
 * @member {Boolean} isBusinessOrder
 * @type {Boolean}
 */
Order.prototype.isBusinessOrder = undefined

/**
 * When true, the order is a seller-fulfilled Amazon Prime order.
 * @member {Boolean} isPrime
 * @type {Boolean}
 */
Order.prototype.isPrime = undefined

/**
 * When true, the order has a Premium Shipping Service Level Agreement. For more information about Premium Shipping orders, refer to \"Premium Shipping Options\" in the Seller Central Help for your marketplace.
 * @member {Boolean} isPremiumOrder
 * @type {Boolean}
 */
Order.prototype.isPremiumOrder = undefined

/**
 * When true, the order is a `GlobalExpress` order.
 * @member {Boolean} isGlobalExpressEnabled
 * @type {Boolean}
 */
Order.prototype.isGlobalExpressEnabled = undefined

/**
 * The order ID value for the order that is being replaced. Returned only if IsReplacementOrder = true.
 * @member {String} replacedOrderId
 * @type {String}
 */
Order.prototype.replacedOrderId = undefined

/**
 * When true, this is a replacement order.
 * @member {Boolean} isReplacementOrder
 * @type {Boolean}
 */
Order.prototype.isReplacementOrder = undefined

/**
 * Indicates the date by which the seller must respond to the buyer with an estimated ship date. Only returned for Sourcing on Demand orders.
 * @member {String} promiseResponseDueDate
 * @type {String}
 */
Order.prototype.promiseResponseDueDate = undefined

/**
 * When true, the estimated ship date is set for the order. Only returned for Sourcing on Demand orders.
 * @member {Boolean} isEstimatedShipDateSet
 * @type {Boolean}
 */
Order.prototype.isEstimatedShipDateSet = undefined

/**
 * When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller.
 * @member {Boolean} isSoldByAB
 * @type {Boolean}
 */
Order.prototype.isSoldByAB = undefined

/**
 * When true, the item within this order was bought and re-sold by Amazon Business EU SARL (ABEU). By buying and instantly re-selling your items, ABEU becomes the seller of record, making your inventory available for sale to customers who would not otherwise purchase from a third-party seller.
 * @member {Boolean} isIBA
 * @type {Boolean}
 */
Order.prototype.isIBA = undefined

/**
 * @member {Address} defaultShipFromLocationAddress
 * @type {Address}
 */
Order.prototype.defaultShipFromLocationAddress = undefined

/**
 * Allowed values for the <code>BuyerInvoicePreference</code> property.
 * @enum {String}
 * @readonly
 */
Order.BuyerInvoicePreferenceEnum = {

  /**
     * value: "INDIVIDUAL"
     * @const
     */
  INDIVIDUAL: 'INDIVIDUAL',

  /**
     * value: "BUSINESS"
     * @const
     */
  BUSINESS: 'BUSINESS'
}

/**
 * The buyer's invoicing preference. Sellers can use this data to issue electronic invoices for orders in Turkey.  **Note**: This attribute is only available in the Turkey marketplace.
 * @member {String} buyerInvoicePreference
 * @type {String}
 */
Order.prototype.buyerInvoicePreference = undefined

/**
 * @member {BuyerTaxInformation} buyerTaxInformation
 * @type {BuyerTaxInformation}
 */
Order.prototype.buyerTaxInformation = undefined

/**
 * @member {FulfillmentInstruction} fulfillmentInstruction
 * @type {FulfillmentInstruction}
 */
Order.prototype.fulfillmentInstruction = undefined

/**
 * When true, this order is marked to be picked up from a store rather than delivered.
 * @member {Boolean} isISPU
 * @type {Boolean}
 */
Order.prototype.isISPU = undefined

/**
 * When true, this order is marked to be delivered to an Access Point. The access location is chosen by the customer. Access Points include Amazon Hub Lockers, Amazon Hub Counters, and pickup points operated by carriers.
 * @member {Boolean} isAccessPointOrder
 * @type {Boolean}
 */
Order.prototype.isAccessPointOrder = undefined

/**
 * @member {MarketplaceTaxInfo} marketplaceTaxInfo
 * @type {MarketplaceTaxInfo}
 */
Order.prototype.marketplaceTaxInfo = undefined

/**
 * The seller’s friendly name registered in the marketplace where the sale took place. Sellers can use this data to issue electronic invoices for orders in Brazil.  **Note**: This attribute is only available in the Brazil marketplace for the orders with `Pending` or `Unshipped` status.
 * @member {String} sellerDisplayName
 * @type {String}
 */
Order.prototype.sellerDisplayName = undefined

/**
 * @member {Address} shippingAddress
 * @type {Address}
 */
Order.prototype.shippingAddress = undefined

/**
 * @member {BuyerInfo} buyerInfo
 * @type {BuyerInfo}
 */
Order.prototype.buyerInfo = undefined

/**
 * @member {AutomatedShippingSettings} automatedShippingSettings
 * @type {AutomatedShippingSettings}
 */
Order.prototype.automatedShippingSettings = undefined

/**
 * Whether the order contains regulated items which may require additional approval steps before being fulfilled.
 * @member {Boolean} hasRegulatedItems
 * @type {Boolean}
 */
Order.prototype.hasRegulatedItems = undefined

/**
 * @member {ElectronicInvoiceStatus} electronicInvoiceStatus
 * @type {ElectronicInvoiceStatus}
 */
Order.prototype.electronicInvoiceStatus = undefined
