/**
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { MoneyType } from './MoneyType.js'
import { OfferCustomerType } from './OfferCustomerType.js'
import { Points } from './Points.js'
import { QuantityDiscountType } from './QuantityDiscountType.js'

/**
 * The BuyBoxPriceType model module.
 * @module pricing_v0/model/BuyBoxPriceType
 * @version v0
 */
export class BuyBoxPriceType {
  /**
   * Constructs a new <code>BuyBoxPriceType</code>.
   * Schema for an individual buybox price.
   * @alias module:pricing_v0/model/BuyBoxPriceType
   * @class
   * @param condition {String} Indicates the condition of the item. For example: New, Used, Collectible, Refurbished, or Club.
   * @param landedPrice {MoneyType}
   * @param listingPrice {MoneyType}
   * @param shipping {MoneyType}
   */
  constructor (condition, landedPrice, listingPrice, shipping) {
    this.condition = condition
    this.landedPrice = landedPrice
    this.listingPrice = listingPrice
    this.shipping = shipping
  }

  /**
   * Constructs a <code>BuyBoxPriceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {BuyBoxPriceType} obj Optional instance to populate.
   * @return {BuyBoxPriceType} The populated <code>BuyBoxPriceType</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new BuyBoxPriceType()
      if (data.hasOwnProperty('condition')) { obj.condition = ApiClient.convertToType(data.condition, 'String') }
      if (data.hasOwnProperty('offerType')) { obj.offerType = OfferCustomerType.constructFromObject(data.offerType) }
      if (data.hasOwnProperty('quantityTier')) { obj.quantityTier = ApiClient.convertToType(data.quantityTier, 'Number') }
      if (data.hasOwnProperty('quantityDiscountType')) { obj.quantityDiscountType = QuantityDiscountType.constructFromObject(data.quantityDiscountType) }
      if (data.hasOwnProperty('LandedPrice')) { obj.landedPrice = MoneyType.constructFromObject(data.LandedPrice) }
      if (data.hasOwnProperty('ListingPrice')) { obj.listingPrice = MoneyType.constructFromObject(data.ListingPrice) }
      if (data.hasOwnProperty('Shipping')) { obj.shipping = MoneyType.constructFromObject(data.Shipping) }
      if (data.hasOwnProperty('Points')) { obj.points = Points.constructFromObject(data.Points) }
      if (data.hasOwnProperty('sellerId')) { obj.sellerId = ApiClient.convertToType(data.sellerId, 'String') }
    }
    return obj
  }
}

/**
 * Indicates the condition of the item. For example: New, Used, Collectible, Refurbished, or Club.
 * @member {String} condition
 * @type {String}
 */
BuyBoxPriceType.prototype.condition = undefined

/**
 * @member {OfferCustomerType} offerType
 * @type {OfferCustomerType}
 */
BuyBoxPriceType.prototype.offerType = undefined

/**
 * Indicates at what quantity this price becomes active.
 * @member {Number} quantityTier
 * @type {Number}
 */
BuyBoxPriceType.prototype.quantityTier = undefined

/**
 * @member {QuantityDiscountType} quantityDiscountType
 * @type {QuantityDiscountType}
 */
BuyBoxPriceType.prototype.quantityDiscountType = undefined

/**
 * @member {MoneyType} landedPrice
 * @type {MoneyType}
 */
BuyBoxPriceType.prototype.landedPrice = undefined

/**
 * @member {MoneyType} listingPrice
 * @type {MoneyType}
 */
BuyBoxPriceType.prototype.listingPrice = undefined

/**
 * @member {MoneyType} shipping
 * @type {MoneyType}
 */
BuyBoxPriceType.prototype.shipping = undefined

/**
 * @member {Points} points
 * @type {Points}
 */
BuyBoxPriceType.prototype.points = undefined

/**
 * The seller identifier for the offer.
 * @member {String} sellerId
 * @type {String}
 */
BuyBoxPriceType.prototype.sellerId = undefined
