/**
 * Selling Partner API for A+ Content Management
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { ContentBadge } from './ContentBadge.js'
import { ContentStatus } from './ContentStatus.js'

/**
 * The ContentMetadata model module.
 * @module apluscontent_v2020_11_01/model/ContentMetadata
 * @version 2020-11-01
 */
export class ContentMetadata {
  /**
   * Constructs a new <code>ContentMetadata</code>.
   * The A+ Content document&#39;s metadata.
   * @alias module:apluscontent_v2020_11_01/model/ContentMetadata
   * @class
   * @param name {String} The A+ Content document's name.
   * @param marketplaceId {String} The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
   * @param status {ContentStatus}
   * @param badgeSet {[ContentBadge]} The set of content badges.
   * @param updateTime {Date} The approximate age of the A+ Content document and metadata.
   */
  constructor (name, marketplaceId, status, badgeSet, updateTime) {
    this.name = name
    this.marketplaceId = marketplaceId
    this.status = status
    this.badgeSet = badgeSet
    this.updateTime = updateTime
  }

  /**
   * Constructs a <code>ContentMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {ContentMetadata} obj Optional instance to populate.
   * @return {ContentMetadata} The populated <code>ContentMetadata</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new ContentMetadata()
      if (data.hasOwnProperty('name')) { obj.name = ApiClient.convertToType(data.name, 'String') }
      if (data.hasOwnProperty('marketplaceId')) { obj.marketplaceId = ApiClient.convertToType(data.marketplaceId, 'String') }
      if (data.hasOwnProperty('status')) { obj.status = ContentStatus.constructFromObject(data.status) }
      if (data.hasOwnProperty('badgeSet')) { obj.badgeSet = ApiClient.convertToType(data.badgeSet, [ContentBadge]) }
      if (data.hasOwnProperty('updateTime')) { obj.updateTime = ApiClient.convertToType(data.updateTime, 'Date') }
    }
    return obj
  }
}

/**
 * The A+ Content document's name.
 * @member {String} name
 * @type {String}
 */
ContentMetadata.prototype.name = undefined

/**
 * The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
 * @member {String} marketplaceId
 * @type {String}
 */
ContentMetadata.prototype.marketplaceId = undefined

/**
 * @member {ContentStatus} status
 * @type {ContentStatus}
 */
ContentMetadata.prototype.status = undefined

/**
 * The set of content badges.
 * @member {[ContentBadge]} badgeSet
 * @type {[ContentBadge]}
 */
ContentMetadata.prototype.badgeSet = undefined

/**
 * The approximate age of the A+ Content document and metadata.
 * @member {Date} updateTime
 * @type {Date}
 */
ContentMetadata.prototype.updateTime = undefined
