/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.finances.v2024_06_19;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing Breakdown
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BreakdownTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Breakdown
        //private Breakdown instance;

        public BreakdownTests()
        {
            // TODO uncomment below to create an instance of Breakdown
            //instance = new Breakdown();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Breakdown
        /// </summary>
        [Fact]
        public void BreakdownInstanceTest()
        {
            // TODO uncomment below to test "IsType" Breakdown
            //Assert.IsType<Breakdown>(instance);
        }

        /// <summary>
        /// Test the property 'BreakdownType'
        /// </summary>
        [Fact]
        public void BreakdownTypeTest()
        {
            // TODO unit test for the property 'BreakdownType'
        }

        /// <summary>
        /// Test the property 'BreakdownAmount'
        /// </summary>
        [Fact]
        public void BreakdownAmountTest()
        {
            // TODO unit test for the property 'BreakdownAmount'
        }

        /// <summary>
        /// Test the property 'Breakdowns'
        /// </summary>
        [Fact]
        public void BreakdownsTest()
        {
            // TODO unit test for the property 'Breakdowns'
        }
    }
}
