/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.finances.v2024_06_19;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing Context
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Context
        //private Context instance;

        public ContextTests()
        {
            // TODO uncomment below to create an instance of Context
            //instance = new Context();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Context
        /// </summary>
        [Fact]
        public void ContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" Context
            //Assert.IsType<Context>(instance);
        }

        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Fact]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }

        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }

        /// <summary>
        /// Test the property 'Asin'
        /// </summary>
        [Fact]
        public void AsinTest()
        {
            // TODO unit test for the property 'Asin'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }

        /// <summary>
        /// Test the property 'QuantityShipped'
        /// </summary>
        [Fact]
        public void QuantityShippedTest()
        {
            // TODO unit test for the property 'QuantityShipped'
        }

        /// <summary>
        /// Test the property 'FulfillmentNetwork'
        /// </summary>
        [Fact]
        public void FulfillmentNetworkTest()
        {
            // TODO unit test for the property 'FulfillmentNetwork'
        }

        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Fact]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }

        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }

        /// <summary>
        /// Test the property 'PaymentReference'
        /// </summary>
        [Fact]
        public void PaymentReferenceTest()
        {
            // TODO unit test for the property 'PaymentReference'
        }

        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Fact]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }

        /// <summary>
        /// Test the property 'DeferralReason'
        /// </summary>
        [Fact]
        public void DeferralReasonTest()
        {
            // TODO unit test for the property 'DeferralReason'
        }

        /// <summary>
        /// Test the property 'MaturityDate'
        /// </summary>
        [Fact]
        public void MaturityDateTest()
        {
            // TODO unit test for the property 'MaturityDate'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'ContextType'
        /// </summary>
        [Fact]
        public void ContextTypeTest()
        {
            // TODO unit test for the property 'ContextType'
        }
    }
}
