/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.finances.v2024_06_19;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing ItemRelatedIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemRelatedIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemRelatedIdentifier
        //private ItemRelatedIdentifier instance;

        public ItemRelatedIdentifierTests()
        {
            // TODO uncomment below to create an instance of ItemRelatedIdentifier
            //instance = new ItemRelatedIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemRelatedIdentifier
        /// </summary>
        [Fact]
        public void ItemRelatedIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemRelatedIdentifier
            //Assert.IsType<ItemRelatedIdentifier>(instance);
        }

        /// <summary>
        /// Test the property 'ItemRelatedIdentifierName'
        /// </summary>
        [Fact]
        public void ItemRelatedIdentifierNameTest()
        {
            // TODO unit test for the property 'ItemRelatedIdentifierName'
        }

        /// <summary>
        /// Test the property 'ItemRelatedIdentifierValue'
        /// </summary>
        [Fact]
        public void ItemRelatedIdentifierValueTest()
        {
            // TODO unit test for the property 'ItemRelatedIdentifierValue'
        }
    }
}
