/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using software.amzn.spapi.Model.finances.v2024_06_19;
using software.amzn.spapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace software.amzn.spapi.Test.Model
{
    /// <summary>
    ///  Class for testing RelatedIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RelatedIdentifierTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RelatedIdentifier
        //private RelatedIdentifier instance;

        public RelatedIdentifierTests()
        {
            // TODO uncomment below to create an instance of RelatedIdentifier
            //instance = new RelatedIdentifier();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RelatedIdentifier
        /// </summary>
        [Fact]
        public void RelatedIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsType" RelatedIdentifier
            //Assert.IsType<RelatedIdentifier>(instance);
        }

        /// <summary>
        /// Test the property 'RelatedIdentifierName'
        /// </summary>
        [Fact]
        public void RelatedIdentifierNameTest()
        {
            // TODO unit test for the property 'RelatedIdentifierName'
        }

        /// <summary>
        /// Test the property 'RelatedIdentifierValue'
        /// </summary>
        [Fact]
        public void RelatedIdentifierValueTest()
        {
            // TODO unit test for the property 'RelatedIdentifierValue'
        }
    }
}
