/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.customerFeedback.v2024_06_01
{
    /// <summary>
    /// Topics from returns for all items in a browse node.
    /// </summary>
    [DataContract(Name = "BrowseNodeReturnTopics")]
    public partial class BrowseNodeReturnTopics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReturnTopics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BrowseNodeReturnTopics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReturnTopics" /> class.
        /// </summary>
        /// <param name="topic">The name of the return feedback topic . (required).</param>
        /// <param name="browseNodeMetrics">browseNodeMetrics (required).</param>
        public BrowseNodeReturnTopics(string topic = default(string), BrowseNodeTrendMetrics browseNodeMetrics = default(BrowseNodeTrendMetrics))
        {
            // to ensure "topic" is required (not null)
            if (topic == null)
            {
                throw new ArgumentNullException("topic is a required property for BrowseNodeReturnTopics and cannot be null");
            }
            this.Topic = topic;
            // to ensure "browseNodeMetrics" is required (not null)
            if (browseNodeMetrics == null)
            {
                throw new ArgumentNullException("browseNodeMetrics is a required property for BrowseNodeReturnTopics and cannot be null");
            }
            this.BrowseNodeMetrics = browseNodeMetrics;
        }

        /// <summary>
        /// The name of the return feedback topic .
        /// </summary>
        /// <value>The name of the return feedback topic .</value>
        [DataMember(Name = "topic", IsRequired = true, EmitDefaultValue = true)]
        public string Topic { get; set; }

        /// <summary>
        /// Gets or Sets BrowseNodeMetrics
        /// </summary>
        [DataMember(Name = "browseNodeMetrics", IsRequired = true, EmitDefaultValue = true)]
        public BrowseNodeTrendMetrics BrowseNodeMetrics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrowseNodeReturnTopics {\n");
            sb.Append("  Topic: ").Append(Topic).Append("\n");
            sb.Append("  BrowseNodeMetrics: ").Append(BrowseNodeMetrics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
