/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.customerFeedback.v2024_06_01
{
    /// <summary>
    /// The return metrics for a certain month.
    /// </summary>
    [DataContract(Name = "BrowseNodeReturnTrendPoint")]
    public partial class BrowseNodeReturnTrendPoint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReturnTrendPoint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BrowseNodeReturnTrendPoint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BrowseNodeReturnTrendPoint" /> class.
        /// </summary>
        /// <param name="dateRange">dateRange (required).</param>
        /// <param name="browseNodeMetrics">browseNodeMetrics (required).</param>
        public BrowseNodeReturnTrendPoint(DateRange dateRange = default(DateRange), BrowseNodeTrendMetrics browseNodeMetrics = default(BrowseNodeTrendMetrics))
        {
            // to ensure "dateRange" is required (not null)
            if (dateRange == null)
            {
                throw new ArgumentNullException("dateRange is a required property for BrowseNodeReturnTrendPoint and cannot be null");
            }
            this.DateRange = dateRange;
            // to ensure "browseNodeMetrics" is required (not null)
            if (browseNodeMetrics == null)
            {
                throw new ArgumentNullException("browseNodeMetrics is a required property for BrowseNodeReturnTrendPoint and cannot be null");
            }
            this.BrowseNodeMetrics = browseNodeMetrics;
        }

        /// <summary>
        /// Gets or Sets DateRange
        /// </summary>
        [DataMember(Name = "dateRange", IsRequired = true, EmitDefaultValue = true)]
        public DateRange DateRange { get; set; }

        /// <summary>
        /// Gets or Sets BrowseNodeMetrics
        /// </summary>
        [DataMember(Name = "browseNodeMetrics", IsRequired = true, EmitDefaultValue = true)]
        public BrowseNodeTrendMetrics BrowseNodeMetrics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrowseNodeReturnTrendPoint {\n");
            sb.Append("  DateRange: ").Append(DateRange).Append("\n");
            sb.Append("  BrowseNodeMetrics: ").Append(BrowseNodeMetrics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
