/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = software.amzn.spapi.Client.OpenAPIDateConverter;

namespace software.amzn.spapi.Model.customerFeedback.v2024_06_01
{
    /// <summary>
    /// The review topic metrics for other child ASINs that have the same parent ASIN. This value is &#x60;null&#x60; if there isn&#39;t any child ASIN metric data.
    /// </summary>
    [DataContract(Name = "ChildAsinMetrics")]
    public partial class ChildAsinMetrics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChildAsinMetrics" /> class.
        /// </summary>
        /// <param name="mostMentions">mostMentions.</param>
        /// <param name="leastMentions">leastMentions.</param>
        public ChildAsinMetrics(ChildAsinMentionMetrics mostMentions = default(ChildAsinMentionMetrics), ChildAsinMentionMetrics leastMentions = default(ChildAsinMentionMetrics))
        {
            this.MostMentions = mostMentions;
            this.LeastMentions = leastMentions;
        }

        /// <summary>
        /// Gets or Sets MostMentions
        /// </summary>
        [DataMember(Name = "mostMentions", EmitDefaultValue = false)]
        public ChildAsinMentionMetrics MostMentions { get; set; }

        /// <summary>
        /// Gets or Sets LeastMentions
        /// </summary>
        [DataMember(Name = "leastMentions", EmitDefaultValue = false)]
        public ChildAsinMentionMetrics LeastMentions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChildAsinMetrics {\n");
            sb.Append("  MostMentions: ").Append(MostMentions).Append("\n");
            sb.Append("  LeastMentions: ").Append(LeastMentions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
