/**
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { BrowseNodeTrendMetrics } from './BrowseNodeTrendMetrics.js'

/**
 * The BrowseNodeReturnTopics model module.
 * @module customerFeedback_2024_06_01/model/BrowseNodeReturnTopics
 * @version 2024-06-01
 */
export class BrowseNodeReturnTopics {
  /**
   * Constructs a new <code>BrowseNodeReturnTopics</code>.
   * Topics from returns for all items in a browse node.
   * @alias module:customerFeedback_2024_06_01/model/BrowseNodeReturnTopics
   * @class
   * @param topic {String} The name of the return feedback topic .
   * @param browseNodeMetrics {BrowseNodeTrendMetrics}
   */
  constructor (topic, browseNodeMetrics) {
    this.topic = topic
    this.browseNodeMetrics = browseNodeMetrics
  }

  /**
   * Constructs a <code>BrowseNodeReturnTopics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {BrowseNodeReturnTopics} obj Optional instance to populate.
   * @return {BrowseNodeReturnTopics} The populated <code>BrowseNodeReturnTopics</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new BrowseNodeReturnTopics()
      if (data.hasOwnProperty('topic')) { obj.topic = ApiClient.convertToType(data.topic, 'String') }
      if (data.hasOwnProperty('browseNodeMetrics')) { obj.browseNodeMetrics = BrowseNodeTrendMetrics.constructFromObject(data.browseNodeMetrics) }
    }
    return obj
  }
}

/**
 * The name of the return feedback topic .
 * @member {String} topic
 * @type {String}
 */
BrowseNodeReturnTopics.prototype.topic = undefined

/**
 * @member {BrowseNodeTrendMetrics} browseNodeMetrics
 * @type {BrowseNodeTrendMetrics}
 */
BrowseNodeReturnTopics.prototype.browseNodeMetrics = undefined
