/**
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { BrowseNodeAllOccurrence } from './BrowseNodeAllOccurrence.js'
import { BrowseNodeAllStarRatingImpact } from './BrowseNodeAllStarRatingImpact.js'

/**
 * The BrowseNodeReviewTopicMetrics model module.
 * @module customerFeedback_2024_06_01/model/BrowseNodeReviewTopicMetrics
 * @version 2024-06-01
 */
export class BrowseNodeReviewTopicMetrics {
  /**
   * Constructs a new <code>BrowseNodeReviewTopicMetrics</code>.
   * The browse node review topic metrics.
   * @alias module:customerFeedback_2024_06_01/model/BrowseNodeReviewTopicMetrics
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>BrowseNodeReviewTopicMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {BrowseNodeReviewTopicMetrics} obj Optional instance to populate.
   * @return {BrowseNodeReviewTopicMetrics} The populated <code>BrowseNodeReviewTopicMetrics</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new BrowseNodeReviewTopicMetrics()
      if (data.hasOwnProperty('occurrencePercentage')) { obj.occurrencePercentage = BrowseNodeAllOccurrence.constructFromObject(data.occurrencePercentage) }
      if (data.hasOwnProperty('starRatingImpact')) { obj.starRatingImpact = BrowseNodeAllStarRatingImpact.constructFromObject(data.starRatingImpact) }
    }
    return obj
  }
}

/**
 * @member {BrowseNodeAllOccurrence} occurrencePercentage
 * @type {BrowseNodeAllOccurrence}
 */
BrowseNodeReviewTopicMetrics.prototype.occurrencePercentage = undefined

/**
 * @member {BrowseNodeAllStarRatingImpact} starRatingImpact
 * @type {BrowseNodeAllStarRatingImpact}
 */
BrowseNodeReviewTopicMetrics.prototype.starRatingImpact = undefined
