/**
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { ApiClient } from '../ApiClient.js'
import { BrowseNodeReviewTopic } from './BrowseNodeReviewTopic.js'

/**
 * The BrowseNodeReviewTopics model module.
 * @module customerFeedback_2024_06_01/model/BrowseNodeReviewTopics
 * @version 2024-06-01
 */
export class BrowseNodeReviewTopics {
  /**
   * Constructs a new <code>BrowseNodeReviewTopics</code>.
   * The 10 most positive and most negative review topics for all items in a browse node.
   * @alias module:customerFeedback_2024_06_01/model/BrowseNodeReviewTopics
   * @class
   */
  constructor () {
  }

  /**
   * Constructs a <code>BrowseNodeReviewTopics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {BrowseNodeReviewTopics} obj Optional instance to populate.
   * @return {BrowseNodeReviewTopics} The populated <code>BrowseNodeReviewTopics</code> instance.
   */
  static constructFromObject (data, obj) {
    if (data) {
      switch (typeof data) {
        case 'string':
          obj = String(data)
          break
        case 'number':
          obj = Number(data)
          break
        case 'boolean':
          obj = Boolean(data)
          break
      }
      obj = obj || new BrowseNodeReviewTopics()
      if (data.hasOwnProperty('positiveTopics')) { obj.positiveTopics = ApiClient.convertToType(data.positiveTopics, [BrowseNodeReviewTopic]) }
      if (data.hasOwnProperty('negativeTopics')) { obj.negativeTopics = ApiClient.convertToType(data.negativeTopics, [BrowseNodeReviewTopic]) }
    }
    return obj
  }
}

/**
 * A list of the most positive review topics. When the `sortBy` query parameter is set to `MENTIONS`, the number of reviews of items within the requested browse node that mention the topic determine the topic's placement in the list. When `sortBy` is set to `STAR_RATING_IMPACT`, the effect that the topic has on the star rating of items within the requested browse node determine placement in the list. This value is `null` if there are not enough positive reviews for the requested browse node.  **Max length:** 10
 * @member {[BrowseNodeReviewTopic]} positiveTopics
 * @type {[BrowseNodeReviewTopic]}
 */
BrowseNodeReviewTopics.prototype.positiveTopics = undefined

/**
 * A list of the most negative review topics. When the `sortBy` query parameter is set to `MENTIONS`, the number of reviews of items within the requested browse node that mention the topic determine the topic's placement in the list. When `sortBy` is set to `STAR_RATING_IMPACT`, the effect that the topic has on the star rating of items within the requested browse node determine placement in the list. This value is `null` if there are not enough negative reviews for the requested browse node.  **Max length:** 10
 * @member {[BrowseNodeReviewTopic]} negativeTopics
 * @type {[BrowseNodeReviewTopic]}
 */
BrowseNodeReviewTopics.prototype.negativeTopics = undefined
