name: Create CSharp SDK Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build]

env:
  SDK_VERSION: ${{ github.event.inputs.newVersionNumber }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        working-directory: ./csharp/sdk/src/software.amzn.spapi
        run: dotnet restore
            
      - name: Build
        working-directory: ./csharp/sdk/src/software.amzn.spapi
        id: build-project
        run: dotnet build --configuration Release --no-restore
  
      - name: Pack
        working-directory: ./csharp/sdk/src/software.amzn.spapi
        id: pack-csharp
        run: |
            dotnet pack ./software.amzn.spapi.csproj --configuration Release

      - name: PushNuget
        working-directory: ./csharp/sdk/src/software.amzn.spapi
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
